### ISSUE TITLE
Look into the Google Map API regarding device location

### ISSUE THREAD

**Issue by thomas-q-raya** [johnbroaddusivccv/TheGroup#2]
The goal for the use of this API is to track the location of a user.

**Comment by johnbroaddusivccv** [comment]
Just an update on this issue -- I am learning how to use the geocoding google maps api which will turn the addresses that zomato gives me into gps coordinates. To do so i will have to use the results from the zomato api and apply that to the ajax call via geocoding google maps.  I have hit a lot of walls but am making progress.
