### ISSUE TITLE
Zomato API: Pull restaurant information.

### ISSUE THREAD

**Issue by thomas-q-raya** [johnbroaddusivccv/TheGroup#3]
The goal for the use of this API is to pull a list of restaurant

**Comment by thomas-q-raya** [comment]
John is currently having issues getting the Zomato and Google Maps APIs to function. May look into using  a different location service's API.

**Comment by johnbroaddusivccv** [comment]
Just an update on this issue -- layne & I did see movement with the apikey provided by zomato yesterday, I aim to have both Zomato & Google Maps Api displaying data in the Dom by the end of the night.
